# Generated by Django 5.0.14 on 2025-12-03 02:31

from django.db import migrations
from django.utils.text import slugify


def populate_default_organizations(apps, schema_editor):
    """
    Create a personal organization for each existing user and link them with UserProfile.
    Optionally update existing tasks to belong to the user's organization.
    """
    User = apps.get_model('auth', 'User')
    Organization = apps.get_model('tasks', 'Organization')
    UserProfile = apps.get_model('tasks', 'UserProfile')
    Task = apps.get_model('tasks', 'Task')
    
    for user in User.objects.all():
        # Create a personal organization for the user
        base_slug = slugify(user.username)
        slug = base_slug
        counter = 1
        
        # Ensure slug uniqueness
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        org, created = Organization.objects.get_or_create(
            name=f"{user.username}'s Organization",
            slug=slug,
            defaults={'description': f"Personal workspace for {user.username}"}
        )
        
        # Create UserProfile linking user to their organization with 'owner' role
        UserProfile.objects.get_or_create(
            user=user,
            organization=org,
            defaults={'role': 'owner'}
        )
        
        # Update existing tasks created by this user to belong to their organization
        Task.objects.filter(created_by__isnull=True).update(
            created_by=user,
            organization=org
        )
        # Also handle tasks that might have been created but not assigned to an org
        Task.objects.filter(created_by=user, organization__isnull=True).update(
            organization=org
        )


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: remove organizations and profiles created by this migration.
    Note: This is a simplified reverse that clears all org data.
    """
    Organization = apps.get_model('tasks', 'Organization')
    UserProfile = apps.get_model('tasks', 'UserProfile')
    Task = apps.get_model('tasks', 'Task')
    
    # Clear organization references from tasks
    Task.objects.all().update(organization=None, created_by=None, assigned_to=None)
    
    # Delete all profiles and organizations
    UserProfile.objects.all().delete()
    Organization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_organization_userprofile_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_default_organizations, reverse_populate),
    ]
